{% set data = load_setup_py_data() %}

package:
  name: awesimsoss
  version: {{ data.get('version') }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - awesimsoss

about:
  home: https://github.com/spacetelescope/awesimsoss
  license: MIT
  summary: 'Data simulator for JWST NIRISS SOSS mode'
  description: |
    This pure Python 3.6+ package produces simulated time-series data for the
    Single Object Slitless Spectroscopy (SOSS) mode of the NIRISS instrument
    onboard the James Webb Space Telescope.
  dev_url: https://github.com/spacetelescope/awesimsoss
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst

extra:
  maintainers:
   - Joe Filippazzo